name: RequestCompression

env:
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

on:
  push:
    # branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./RequestCompression

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        if [[ $VERSION =~ ^[0-9]+\.[:0-9]+\.[1-9+]$ ]]; then
          echo ::set-output name=VERSION::$VERSION
        else 
          echo ::set-output name=VERSION::0.0.0
        fi
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ steps.get_version.outputs.VERSION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release 

    - name: Publish NuGet
      run: dotnet nuget push ./**/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_API_KEY
      if: startsWith(github.ref, 'refs/tags/v')
